### ISSUE TITLE
Subsetting Data Prior to Running MOFA

### ISSUE THREAD

**Issue by whitleyo** [bioFAM/MOFA#13]
Hi,

I noticed in your paper that you subsetted for DNA methylation probes from the illumina array with the top 1% of variance, as well as the RNA-seq genes with the top 20% of variance across samples. On my own I found out that if I didn't do this, the factors found would be dominated by DNA methylation for my own data, the details of which are discussed in the next paragraph. I'm wondering why the subsetting is required for the MOFA model to identify factors explaining variance in both datatypes.

 When I initially tried running MOFA on the dataset I have (~50 samples, Illumina EPIC methylation array, RNA-seq), I didn't do this subsetting, and I ended up getting 2 factors explaining about 50% of the DNA methylation data's variance and virtually none of the RNA-seq data's variance. I reran MOFA, but with the same data matrices subsetted for the top 20% variant genes for RNA-seq and top 1% variant probes for DNA methylation, and obtained 9 factors, two of which explained a good portion of the RNA-seq data's variance.

Here's the plot.

![image](https://user-images.githubusercontent.com/25909144/37911571-63ba1560-30de-11e8-8b63-d0e46c73544e.png)

**Comment by rargelaguet** [comment]
Hi,
a few things to consider.
(1) The model has a problem when the views are too imbalanced, meaning that one assay is order of magnitudes bigger than another (i.e. 100k vs 100). For this reason we subset the methylation data (>100k features) with a stricter threshold than RNA (20k features). We are thinking on approaches to address this, but for now the best solution is to have balanced views.
(2)  Features that have little variance usually don't contribute to the learning of factors. Hence, we always remove genes with average mean expression closer to 0 as well as features with little variability.

Overall, I recommend you do subset the methylation data. If you don't want to do it, perhaps running the model with a lot of factors might capture the RNA-seq variation properly.

**Comment by ttriche** [comment]
DNA methylation data often benefits from being "blocked" into contiguous
regions of correlated variability.  This works particularly well for
whole-genome bisulfite sequencing data, which is otherwise somewhat
intractable.

How to best perform the reduction is an open research topic, but several
front-ends are worth considering (e.g. DMRcate, dmrseq, SMART) and could
easily be fed to the MOFA package itself.  This type of reduction
(summarization of high-variability regions into blocks) simultaneously
filters more aggressively and compresses more usefully the differences
between samples, consistent with Bourgon's PNAS paper.


--t

**Comment by rargelaguet** [comment]
Yeah, good idea Tim.
I think Izaskun Mallona (https://imallona.bitbucket.io/contact.html) was trying this. Doing dimensionality reduction in the methylation data into a few thousand "independent" blocks and fit them into MOFA.
